thdwlsgus0/algo_spot

- 진현/2016년.js
- 진현/다트게임.js
- 진현/위장.js
- 진현/조이스틱.js
> 알고리즘 스터디 1주차 문제 풀이

- 김동용_kingyong9169/[PG]2016년.js
- 김동용_kingyong9169/[PG]다트게임.js
- 김동용_kingyong9169/[PG]위장.js
- 김동용_kingyong9169/[PG]조이스틱.js
조이스틱(그리디)은 너무 어려워서 좌우 움직임은 구글링 통해서 해결했습니다. 그래도 아직 모르겠습니다ㅠㅠ
> 7월 4주차 js알고리즘

- 김동용_kingyong9169/[PG]가장 큰 수.js
- 김동용_kingyong9169/[PG]비밀지도.js
- 김동용_kingyong9169/[PG]완주하지 못한 선수.js
- 김동용_kingyong9169/[PG]크레인 인형뽑기 게임.js
> 7월 5주차 알고리즘 스터디입니다.

- 보물지도.js
- 인형뽑기.js
교통사고와 코로나 확진자와 동선이겹치는등 다사다난한 일주일이었습니다...ㅠㅠ
급하게 로직을 짜다보니 한문제는 테스트케이스만 되는등 제대로 작성을 못했습니다
일단 한데까지 올렸습니다!
> 7월5주차 입니다 

- 김동용_kingyong9169/[PG]소수 찾기.js
- 김동용_kingyong9169/[PG]숫자 문자열과 영단어.js
- 김동용_kingyong9169/[PG]실패율.js
> 8월 1주차 알고리즘 스터디입니다.

- 진현/3주차/소수 찾기.js
- 진현/3주차/숫자 문자열과 영단어.js
- 진현/3주차/실패율.js
> 알고리즘 스터디 3주차 풀이 

- 김동용_kingyong9169/[PG]문자열 내 마음대로 정렬하기.js
- 김동용_kingyong9169/[PG]체육복.js
- 김동용_kingyong9169/[PG]키패드 누르기.js
- 김동용_kingyong9169/[PG]타겟 넘버.js
체육복의 경우 cpp로 해결했던 것을 js로 옮겼습니다. 추후에 리팩토링할 예정입니다.
> 8월 2주차 알고리즘 스터디입니다.

- 김동용_kingyong9169/[PG]두 개 뽑아서 더하기.js
- 김동용_kingyong9169/[PG]신규 아이디 추천.js
- 김동용_kingyong9169/[PG]카펫.js
- 김동용_kingyong9169/[PG]프린터.js
신규 아이디 추천을 solving 중 입니다. 바빠서 많이 늦었습니다ㅠㅠ
> 8월 3주차 알고리즘입니다.

- 낙현/두 개 뽑아서 더하기.js
- 낙현/신규 아이디 추천.js
- 낙현/카펫.js
Level 1문제중 2문제는 해결했지만 
신규 아이디 추천에서 테스트케이스 6개가 오류가나서 못풀었습니다 ㅠㅠ
> 8월3주차 풀이입니다,

- 김동용_kingyong9169/[PG]내적.js
- 김동용_kingyong9169/[PG]다리를 지나는 트럭.js
- 김동용_kingyong9169/[PG]예산.js
- 김동용_kingyong9169/[PG]오픈채팅방.js
이번주에 바빠서 오픈채팅방은 아직 solve중 입니다ㅠㅠ
> 8월 4주차 알고리즘입니다.

- juyeong/[2019카카오]오픈채팅방.js
- juyeong/[S&W]예산.js
- juyeong/[스택&큐]다리를지나는트럭.js
- juyeong/[월간코드챌린지]내적.js
> 8월 4주차 알고리즘 문제 풀이입니다.

- juyeong/[2018카카오]캐시.js
- juyeong/[2020카카오]문자열압축.js
- juyeong/[연습]콜라츠추측.js
- juyeong/[정렬]H-index.js
> 9월 1주차 알고리즘 풀이입니다.

- 낙현/거리두기 확인하기.js
> 8주차 알고리즘 문제풀이

- juyeong/[2021카카오]메뉴리뉴얼.js
- juyeong/[2021카카오채용연계]거리두기 확인.js
- juyeong/[카카오]키패드.js
매뉴 리뉴얼은 푸는 중입니다
이전문제인 키패드 문제는 eslint가 자동적용돼서 스테이징 됐습니다...!
> 9월 2주차 알고리즘 풀이

- juyeong/[연습문제]N개의최소공배수.js
- juyeong/[연습문제]최댓값과 최솟값.js
> 9월 3주차 추석 알고리즘 문제 풀이입니다.

- 김동용_kingyong9169/[PG]N개의 최소공배수.js
- 김동용_kingyong9169/[PG]메뉴 리뉴얼.js
- 김동용_kingyong9169/[PG]최댓값과 최솟값.js
이제서야 해결했네요.. 나머지 문제도 풀어서 커밋하겠습니다!
> 9월 1주차, 3주차 알고리즘 풀이입니다.

- 김동용_kingyong9169/[PG]2021 우테코 데모.js
- 김동용_kingyong9169/[PG]거리두기 확인하기.js
- 김동용_kingyong9169/[PG]괄호 회전하기.js
- 김동용_kingyong9169/[PG]교점에 별 만들기.js
- 김동용_kingyong9169/[PG]수식 최대화.js
- 김동용_kingyong9169/[PG]짝수와 홀수.js
- 김동용_kingyong9169/[PG]평균 구하기.js
`거리두기 확인하기, 교점에 별 만들기`는 해결하지 못했습니다!
제외하고 봐주시면 감사하겠습니다!
> 10월 4주차 알고리즘 문제풀이입니다.

- 김동용_kingyong9169/[PG]압축.js
- 김동용_kingyong9169/[PG]이진 변환 반복하기.js
- 김동용_kingyong9169/[PG]튜플.js
> 11월 1주차 알고리즘 문제풀이입니다.

- 진현/12주차/[3차] 압축.js
- 진현/12주차/튜플.js
> 11월 1주차 알고리즘 문제풀이입니다

- 진현/13주차/올바른괄호.js
- 진현/13주차/이진변환반복하기.js
> 11월 2주차 알고리즘 문제풀이입니다.

- 진현/14주차/로또의 최고 순위와 최저 순위.js
- 진현/14주차/멀쩡한사각형.js
- 진현/14주차/큰수만들기.js
> 11월 3주차 알고리즘 문제풀이입니다.

- juyeong/[2019 카카오 블라인드][3차]압축.js
- juyeong/[2021 Dev]로또의 최고 순위와 최저 순위.js
- juyeong/[sw2019]멀쩡한 사각형.js
- juyeong/[연습문제]다음 큰 숫자.js
- juyeong/[탐욕법]구명보트.js
- juyeong/[탐욕법]큰 수 만들기.js
> 11월 3주차 알고리즘 문제풀이 입니다.

- 김동용_kingyong9169/[PG]배달.js
- 김동용_kingyong9169/[PG]스킬트리.js
> 11월 4주차 알고리즘 문제풀이입니다.

- juyeong/[2018 KAKAO BLIND][3차]n진수게임.js
- juyeong/[s-w-2018]배달.js
- juyeong/[s-w-2018]스킬트리.js
- juyeong/[연습문제]땅따먹기.js
> 12월 4주차 알고리즘 문제 풀이입니다.

- 진현/16주차/n진수 게임.js
- 진현/16주차/땅따먹기.js
> 12월 4주차 알고리즘 문제풀이입니다. 

- 김동용_kingyong9169/[PG]124나라의 숫자.js
- 김동용_kingyong9169/[PG]n진수 게임.js
- 김동용_kingyong9169/[PG]땅따먹기.js
> 12월 4주차 알고리즘 문제풀이입니다.

- 진현/17주차/예상대진표.js
- 진현/17주차/프렌즈4블록.js
> 12월 5주차 알고리즘 문제풀이입니다.

- juyeong/[2017 팁스타운]예상 대진표.js
- juyeong/[2018 KAKAO][1차] 프렌즈 4블록.js
- juyeong/[s-w-2018]배달.js
> 12월 5주차 알고리즘 문제 풀이입니다.

- 진현/18주차/영어끝말잇기.js
- 진현/18주차/후보키.js
- 후보키는 솔직히 level3급인데요..? ㅋㅋㅋㅋㅋ 어렵네요
> 1월 1주차 알고리즘 문제 풀이입니다.

- 김동용_kingyong9169/[PG]2개 이하로 다른 비트.js
- 김동용_kingyong9169/[PG]거리두기 확인하기.js
- 김동용_kingyong9169/[PG]모음사전.js
- 김동용_kingyong9169/[PG]방문 길이.js
- 김동용_kingyong9169/[PG]삼각 달팽이.js
- 김동용_kingyong9169/[PG]영어 끝말잇기.js
- 김동용_kingyong9169/[PG]점프와 순간 이동.js
- 김동용_kingyong9169/[PG]파일명 정렬.js
- 김동용_kingyong9169/[PG]후보키.js
> 1월 1주차 알고리즘 문제풀이입니다.
